<?xml version="1.0" encoding="utf-8"?><Database Name="map_updates" Class="MUDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=mapupdates.database.windows.net;Initial Catalog=map_updates;User ID=updates_administrator;Connect Timeout=60;Encrypt=True;TrustServerCertificate=False" SettingsObjectName="FSV42_FullMapReplacement.Properties.Settings" SettingsPropertyName="map_updatesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.atmos_mapupdate" Member="atmos_mapupdates">
    <Type Name="atmos_mapupdate">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="region" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="computer_name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>